author = "Kirill Bobyrev"
baseURL = "https://kirillbobyrev.com/"
enableRobotsTXT = true
googleAnalytics = "G-RHCZGDQQJR"
languageCode = "en"
theme = "hugo-bearblog"
title = "Kirill Bobyrev"
enableEmoji = true

[permalinks]
  blog = "/:slug"
  tags = "/blog/:slug"

[params]
  description = "Kirill Bobyrev's blog about software engineering and my hobbies"
  favicon = "icons/favicon.ico"
  title = "Kirill Bobyrev blog"
  hideMadeWithLine = true
