author = "Kirill Bobyrev"
baseURL = "https://kirillbobyrev.com/"
enableRobotsTXT = true
googleAnalytics = "G-RHCZGDQQJR"
languageCode = "en"
theme = "hugo-bearblog"
title = "Kirill Bobyrev"
unsafe = true
enableEmoji = true

[permalinks]
  blog = "/:slug"
  tags = "/blog/:slug"

[params]
  description = "Kirill Bobyrev's blog about software engineering and my hobbies"
  favicon = "icons/favicon.ico"
  title = "Kirill Bobyrev blog"
  hideMadeWithLine = true

# Configure Chroma syntax highlighting.
[markup]
  [markup.highlight]
    guessSyntax = true
    style = "github"
    tabWidth = 2
