baseURL = "https://kirillbobyrev.com/"
enableRobotsTXT = true
googleAnalytics = "G-RHCZGDQQJR"
languageCode = "en"
theme = "minimis"
enableEmoji = true
title = "Kirill Bobyrev personal website"

[params]
  author = "Kirill Bobyrev"
  description = "Kirill Bobyrev's blog about software engineering and hobbies"

# Configure Chroma syntax highlighting.
[markup]
  [markup.highlight]
    guessSyntax = true
    style = "github"
    tabWidth = 2
