baseURL = "https://kirillbobyrev.com/"
enableRobotsTXT = true
googleAnalytics = "G-RHCZGDQQJR"
languageCode = "en"
title = "Kirill Bobyrev blog"

# TODO: Add resume and my GSoC paper to static resources.
# TODO: Add nice image of myself.
# TODO: Add image for Twitter cards preview.
# https://gohugo.io/templates/internal/#configure-twitter-cards

[params]
  author = "Kirill Bobyrev"
  description = "Kirill Bobyrev blog about programming and other things"
  keywords = [
    "blog",
    "programming",
    "computer-science",
    "developer",
    "personal",
    "startups",
  ]

# Configure Chroma with sensible defaults.
[markup]
  [markup.highlight]
    codeFenses = true
    guessSyntax = true
    lineNoStart = 0
    lineNos = true
    style = "github"
    tabWidth = 2

# Social links
[[params.social]]
  icon = "fab fa-github fa-2x"
  name = "Github"
  url = "https://github.com/kirillbobyrev/"
  weight = 0
[[params.social]]
  icon = "fab fa-twitter fa-2x"
  name = "Twitter"
  url = "https://twitter.com/kirillbobyrev/"
  weight = 1
[[params.social]]
  icon = "fab fa-linkedin fa-2x"
  name = "LinkedIn"
  url = "https://linkedin.com/in/kirillbobyrev/"
  weight = 2
[[params.social]]
  icon = "fab fa-instagram fa-2x"
  name = "Instagram"
  url = "https://instagram.com/cybobyrev/"
  weight = 3
[[params.social]]
  icon = "fab fa-telegram fa-2x"
  name = "Telegram"
  url = "https://t.me/kirillbobyrev/"
  weight = 4
