baseURL = "https://kirillbobyrev.com/"
enableRobotsTXT = true
googleAnalytics = "G-RHCZGDQQJR"
languageCode = "en"
title = "Kirill Bobyrev blog"

# TODO: Add nice image of myself.
# TODO: Add image for Twitter cards preview.
# https://gohugo.io/templates/internal/#configure-twitter-cards
# TODO: Add favicon with my surname initial.

[params]
  author = "Kirill Bobyrev"
  description = "Kirill Bobyrev's blog about software engineering and my hobbies"
  keywords = [
    "blog",
    "programming",
    "computer-science",
    "developer",
    "personal",
    "startups",
  ]

# Configure Chroma syntax highlighting.
[markup]
  [markup.highlight]
    codeFenses = true
    guessSyntax = true
    style = "github"
    tabWidth = 2
    linenos = true

# Social links.
[[params.social]]
  icon = "fab fa-github fa-2x"
  name = "GitHub"
  url = "https://github.com/kirillbobyrev/"
  weight = 0
[[params.social]]
  icon = "fab fa-linkedin fa-2x"
  name = "LinkedIn"
  url = "https://linkedin.com/in/kirillbobyrev/"
  weight = 1
[[params.social]]
  icon = "fab fa-twitter fa-2x"
  name = "Twitter"
  url = "https://twitter.com/kirillbobyrev/"
  weight = 2
