baseURL = "https://kirillbobyrev.com/"
languageCode = "en"
googleAnalytics = "G-296464358"
enableRobotsTXT = true

# TODO: Add resume and my GSoC paper to static resources.
# TODO: Add nice image of myself.
# TODO: Add image for Twitter cards preview.
# https://gohugo.io/templates/internal/#configure-twitter-cards

[params]
  author = "Kirill Bobyrev"
  description = "Kirill Bobyrev personal blog"
  keywords = [
    "blog",
    "programming",
    "computer-science",
    "developer",
    "personal",
    "startups",
  ]

# Configure Chroma with sensible defaults.
[markup]
  [markup.highlight]
    style = 'github'
    codeFenses = true

[taxonomies]
  tag = "tags"

# Social links
[[params.social]]
  icon = "fab fa-github fa-2x"
  name = "Github"
  url = "https://github.com/kirillbobyrev/"
  weight = 0
[[params.social]]
  icon = "fab fa-twitter fa-2x"
  name = "Twitter"
  url = "https://twitter.com/kirillbobyrev/"
  weight = 1
[[params.social]]
  icon = "fab fa-linkedin fa-2x"
  name = "LinkedIn"
  url = "https://linkedin.com/in/kirillbobyrev/"
  weight = 2
[[params.social]]
  icon = "fab fa-facebook fa-2x"
  name = "Facebook"
  url = "https://facebook.com/cybobyrev/"
  weight = 3
[[params.social]]
  icon = "fab fa-instagram fa-2x"
  name = "Instagram"
  url = "https://instagram.com/cybobyrev/"
  weight = 4
[[params.social]]
  icon = "fab fa-telegram fa-2x"
  name = "Telegram"
  url = "https://t.me/kirillbobyrev/"
  weight = 5
[[params.social]]
  icon = "fab fa-vk fa-2x"
  name = "VK"
  url = "https://vk.com/kirillbobyrev/"
  weight = 6
[[params.social]]
  icon = "fab fa-goodreads fa-2x"
  name = "Goodreads"
  url = "https://goodreads.com/kirillbobyrev/"
  weight = 7
[[params.social]]
  icon = "fas fa-chess-rook fa-2x"
  name = "Chess"
  url = "https://lichess.org/@/kirillbobyrev/"
  weight = 8

[menu]
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = -2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = -1
