name = "Minimis"
license = "Apache 2.0"
licenselink = "https://github.com/kirillbobyrev/kirillbobyrev.com/blob/master/LICENSE"
description = "Minimalistic Hugo blog theme"
homepage = "https://github.com/kirillbobyrev/kirillbobyrev.com"
tags = ["blog", "minimalistic"]
features = [
  "google-analytics",
  "syntax-highlighting",
  "reading-time",
]
min_version = "0.73"

pygmentsStyle = "github"
pygmentsCodefences = true
pygmentsCodefencesguesssyntax = true

[author]
  name = "Kirill Bobyrev"
  homepage = "https://kirillbobyrev.com"
